version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: rateCalculator
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    container_name: express_application
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://myuser:mypassword@mongodb:27017/rateCalculator
    command: node server.js

volumes:
  mongodb_data:


